# Generated by Django 4.0.6 on 2022-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagebd',
            options={'ordering': ['-created_news'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='created_news',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикаций'),
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публикация новости'),
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mainpagebd',
            name='updated_news',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменений'),
        ),
    ]
