# Generated by Django 4.0.6 on 2022-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mainpagebd_options_alter_mainpagebd_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagebd',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
